/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Departament;
import DAL.Departament.DepException;
import DAL.Departament.DepRepository;
import Model.DepartmentTableModel;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import static java.lang.Character.isAlphabetic;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author vega
 */
public class AddDepartments extends javax.swing.JInternalFrame {
    
    DepRepository depRepository = new DepRepository();
    DepartmentTableModel depTableModel = new DepartmentTableModel();
    /**
     * Creates new form AddDepartaments
     */
    public AddDepartments() {
        initComponents();
        getContentPane().setBackground(Color.white);
        tabelaLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addDepButton = new javax.swing.JButton();
        txtDepartament = new javax.swing.JTextField();
        deleteDepButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Department Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 2, 12))); // NOI18N
        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(902, 462));

        jLabel1.setText("Department");

        addDepButton.setText("Add ");
        addDepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDepButtonActionPerformed(evt);
            }
        });

        txtDepartament.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDepartamentKeyPressed(evt);
            }
        });

        deleteDepButton.setText("Delete");
        deleteDepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDepButtonActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDepartament, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addDepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(deleteDepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDepartament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(addDepButton)
                    .addComponent(deleteDepButton)
                    .addComponent(jButton1))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteDepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDepButtonActionPerformed
        // TODO add your handling code here:
         try{
            int row = tabela.getSelectedRow();
            if(row > -1){
                Object [] ob = {"Yes","No"};
                int i = javax.swing.JOptionPane.showOptionDialog(this, "Do you want to delete it?", "Delete:", JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
                if(i==0){
                    Departament dep = this.depTableModel.getDepartment(row);
                    depRepository.remove(dep);
                    tabelaLoad();
                    emptyObject();
                    JOptionPane.showMessageDialog(this, "Document has been deleted succesfully!");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"You haven't selected nothing to delete!");
            }
        }catch(DepException pe){
            JOptionPane.showMessageDialog(this, pe.getMessage());
        }
    }//GEN-LAST:event_deleteDepButtonActionPerformed

    public void emptyObject() {
       tabela.clearSelection();
        txtDepartament.setText("");
    }
    
    private void tabelaLoad() {
        List<Departament> lista = depRepository.findAll();
        depTableModel.add(lista);
        tabela.setModel(depTableModel);
        depTableModel.fireTableDataChanged();
        tabelaSelectedIndexChange();

    }
    
    private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = tabela.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    Departament dep = depTableModel.getDepartment(selectedIndex);

                    txtDepartament.setText(dep.getName()); 
                }
            }
        });
    }
    
    private void addDepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDepButtonActionPerformed
        // TODO add your handling code here:
         
        
         try {
            int row = tabela.getSelectedRow();
            if (txtDepartament.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please write department:", "Department:", JOptionPane.ERROR_MESSAGE);
            }else {
                if (row == -1) {
                    Departament dep = new Departament();
                     dep.setName(txtDepartament.getText());
                    depRepository.create(dep);
                    JOptionPane.showMessageDialog(this, "Department has been saved!");
                } else {
                    Departament dep = this.depTableModel.getDepartment(row);
                     dep.setName(txtDepartament.getText());
                    depRepository.edit(dep);
                    JOptionPane.showMessageDialog(this, "Department has been edited!");
                }
                emptyObject();
                tabelaLoad();
            };

        } catch (DepException pe) {
            JOptionPane.showMessageDialog(this, pe.getMessage());
        }
        
    }//GEN-LAST:event_addDepButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        emptyObject();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDepartamentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepartamentKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(isAlphabetic(c) || c == KeyEvent.VK_BACKSPACE){
            txtDepartament.setEditable(true);
        }
        else{
            txtDepartament.setEditable(false);
        }
    }//GEN-LAST:event_txtDepartamentKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDepButton;
    private javax.swing.JButton deleteDepButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtDepartament;
    // End of variables declaration//GEN-END:variables
}
