/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Category;
import BL.Data;
import BL.Departament;
import BL.User;
import DAL.Categories.CatRepository;
import DAL.Departament.DepRepository;
import DAL.DmsException;
import DAL.DmsRepository;
import DAL.FileType.FtRepository;
import DAL.User.UserRepository;
import Methods.Utils;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import static java.lang.Character.isAlphabetic;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import models.CustomComboBoxModel;
/**
 *
 * @author vega
 */
public class AddDocument extends javax.swing.JInternalFrame {
        
        UserRepository userRepository = new UserRepository();
        DepRepository depRepository = new DepRepository();
        CatRepository catRepository = new CatRepository();
        DmsRepository dmsRepository = new DmsRepository();
        FtRepository ftRepository = new FtRepository(); // file types
       
        CustomComboBoxModel userComboBoxModel = null;
        CustomComboBoxModel departamentComboBoxModel = null;
        CustomComboBoxModel categoryComboBoxModel = null;
        
        List <String> allowedFileTypes;
        
        String Path = null;
        Path target =null;
        String filename = null; 
        File choosenFile = null;
        
        JFileChooser chooser = new JFileChooser();
    
    public AddDocument() {
        this.allowedFileTypes = ftRepository.fileTypes();
        initComponents();
        getContentPane().setBackground(Color.white);
        loadComboBoxs();     
    }
    
    public void emptyObject() {
        chooser.cancelSelection();
        target = null;
        userComboBox.setSelectedItem(null);
        userComboBox.repaint();
        departmentComboBox.setSelectedItem(null);
        departmentComboBox.repaint();
        categoryComboBox.setSelectedItem(null);
        categoryComboBox.repaint();
        txtDescription.setText("");
    }
     
    public void loadComboBoxs(){
        List <User> users = userRepository.findAll();
        List <Departament> departaments = depRepository.findAll();
        List <Category> category = catRepository.findAll();
        
        userComboBoxModel = new CustomComboBoxModel(users);
        departamentComboBoxModel = new CustomComboBoxModel(departaments);
        categoryComboBoxModel = new CustomComboBoxModel(category);
        
        userComboBox.setModel(userComboBoxModel);
        departmentComboBox.setModel(departamentComboBoxModel);
        categoryComboBox.setModel(categoryComboBoxModel);
        
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EdpGroup = new javax.swing.ButtonGroup();
        EapGroup = new javax.swing.ButtonGroup();
        EupGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        choosenFileButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        forbidden1 = new javax.swing.JRadioButton();
        modify1 = new javax.swing.JRadioButton();
        view1 = new javax.swing.JRadioButton();
        admin1 = new javax.swing.JRadioButton();
        forbidden3 = new javax.swing.JRadioButton();
        forbidden4 = new javax.swing.JRadioButton();
        view4 = new javax.swing.JRadioButton();
        modify3 = new javax.swing.JRadioButton();
        modify4 = new javax.swing.JRadioButton();
        admin3 = new javax.swing.JRadioButton();
        admin4 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        userComboBox = new javax.swing.JComboBox<>();
        departmentComboBox = new javax.swing.JComboBox<>();
        choseDepartmentComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        view3 = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Document", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(600, 450));
        setRequestFocusEnabled(false);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jLabel1.setText("File Location ");

        choosenFileButton.setText("Choose Files");
        choosenFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosenFileButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Assign to owner");

        jLabel3.setText("Assign to department");

        jLabel4.setText("Category");

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categories" }));
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Permissions");

        EdpGroup.add(forbidden1);
        forbidden1.setToolTipText("");
        forbidden1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forbidden1ActionPerformed(evt);
            }
        });

        EdpGroup.add(modify1);
        modify1.setToolTipText("");

        EdpGroup.add(view1);
        view1.setSelected(true);
        view1.setToolTipText("");

        EdpGroup.add(admin1);
        admin1.setToolTipText("");

        EapGroup.add(forbidden3);
        forbidden3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forbidden3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        EupGroup.add(forbidden4);

        EupGroup.add(view4);
        view4.setSelected(true);

        EapGroup.add(modify3);
        modify3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modify3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modify3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify3ActionPerformed(evt);
            }
        });

        EupGroup.add(modify4);

        EapGroup.add(admin3);
        admin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        EupGroup.add(admin4);

        jLabel6.setText("Description");

        txtDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescriptionKeyPressed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        userComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Users" }));

        departmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Departments" }));
        departmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentComboBoxActionPerformed(evt);
            }
        });

        choseDepartmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Department" }));
        choseDepartmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choseDepartmentComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setText(" Edit Department Permissions");

        jLabel12.setText(" Edit User Permissions");

        jLabel14.setText("User, Admin");

        jLabel15.setText("User, User");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("  Forbidden");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(" View");
        jLabel17.setPreferredSize(new java.awt.Dimension(54, 14));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Modify");
        jLabel18.setPreferredSize(new java.awt.Dimension(54, 14));
        jLabel18.setVerifyInputWhenFocusTarget(false);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(" Admin");
        jLabel19.setPreferredSize(new java.awt.Dimension(54, 14));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("  Forbidden");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText(" View");
        jLabel21.setPreferredSize(new java.awt.Dimension(54, 14));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Modify");
        jLabel22.setPreferredSize(new java.awt.Dimension(54, 14));
        jLabel22.setVerifyInputWhenFocusTarget(false);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText(" Admin");
        jLabel23.setPreferredSize(new java.awt.Dimension(54, 14));

        EapGroup.add(view3);
        view3.setSelected(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departmentComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choosenFileButton, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(forbidden3)
                                                    .addComponent(forbidden4)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(jLabel16)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(view3)
                                                    .addComponent(view4))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(modify3)
                                                    .addComponent(modify4))
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(admin4)
                                                    .addComponent(admin3)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(choseDepartmentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(forbidden1)
                                                .addGap(39, 39, 39)
                                                .addComponent(view1)
                                                .addGap(39, 39, 39)
                                                .addComponent(modify1)
                                                .addGap(39, 39, 39)
                                                .addComponent(admin1))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(choosenFileButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(choseDepartmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(forbidden3)
                                    .addComponent(modify3)
                                    .addComponent(admin3)))
                            .addComponent(view3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(forbidden4)
                            .addComponent(view4)
                            .addComponent(modify4)
                            .addComponent(admin4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SubmitButton))
                    .addComponent(forbidden1)
                    .addComponent(view1)
                    .addComponent(modify1)
                    .addComponent(admin1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choosenFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosenFileButtonActionPerformed
        // TODO add your handling code here:
    
        choosenFile = chooseFile();
        if(choosenFile == null){
            return;
        }
        if(choosenFile.length() > 72374601)//250*1024*1024=262144000
        {
            chooser.cancelSelection();
            choosenFile = null;
           
            JOptionPane.showMessageDialog(this, "Files larger than 250MB are not allowed!");
            return;
        }
        else if (!isAllowedFile(choosenFile)) 
        {
            chooser.cancelSelection();
            choosenFile = null;
           
            JOptionPane.showMessageDialog(this, "This file type is not allowed!");
            return;
        }
        
        Path movefrom = Utils.getPathFrom(choosenFile);
        
        Utils.makeDirIfNotExists("C:\\DMS-Files\\");
        
        target = FileSystems.getDefault().getPath("C:\\DMS-Files\\" + Utils.getUniqueName(choosenFile.getName()));
        
        try {
            Files.copy(movefrom, target, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException ex) {
            Logger.getLogger(AddDocument.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_choosenFileButtonActionPerformed
    
    
    
    private boolean isAllowedFile(File file) 
    {
        return allowedFileTypes.contains(Utils.getFileExtension(file));
    }
    
    private File chooseFile()
    {
        int returnVal = chooser.showOpenDialog(null);
        return chooser.getSelectedFile();
    }
    
    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void forbidden1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forbidden1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forbidden1ActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        try{
            if (choosenFile == null) {
                JOptionPane.showMessageDialog(this, "Please select a File:", "File:", JOptionPane.ERROR_MESSAGE);
            }else if (target == null) {
                JOptionPane.showMessageDialog(this, "Please select a File:", "File:", JOptionPane.ERROR_MESSAGE);
            }else if (userComboBox.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Please choose the Owner:", "Assign to owner:", JOptionPane.ERROR_MESSAGE);
            }else if (departmentComboBox.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Please choose the Departament:", "Assign to department:", JOptionPane.ERROR_MESSAGE);
            }else if (categoryComboBox.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Please choose the Category:", "Category:", JOptionPane.ERROR_MESSAGE);
            }else if (txtDescription.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please write the Description:", "Description:", JOptionPane.ERROR_MESSAGE);
            }else{
                if(!((userComboBox.getSelectedIndex() == -1)) || (departmentComboBox.getSelectedIndex() == -1) || (choosenFile == null) ||(target == null) || (categoryComboBox.getSelectedIndex() == -1) || (txtDescription.getText().equals("")))
                {
                    Data data = new Data();
                    System.out.println(chooser);
                    User user = (User) userComboBox.getSelectedItem();
                    Departament departament = (Departament) departmentComboBox.getSelectedItem();
                    Category category = (Category) categoryComboBox.getSelectedItem();

                    data.setCategory(category);

                    data.setCreated(new Date());

                    data.setDepartment(departament);

                    data.setDescription(txtDescription.getText());

                    data.setOwner(user);

                    data.setStatus(true);

                    data.setIsDeleted(false);

                    data.setPath(target.toString());

                    data.setRealname(choosenFile.getName());

                    dmsRepository.create(data);

                    JOptionPane.showMessageDialog(null, "Document is saved successfully." );
                }
            emptyObject();
            }
        } catch (DmsException ex) {
            Logger.getLogger(AddDocument.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed
    
    
    
    private void modify3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modify3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modify3ActionPerformed

    private void choseDepartmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choseDepartmentComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choseDepartmentComboBoxActionPerformed

    private void departmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentComboBoxActionPerformed

    private void txtDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescriptionKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(isAlphabetic(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_SPACE){
            txtDescription.setEditable(true);
        }
        else{
            txtDescription.setEditable(false);
        }
    }//GEN-LAST:event_txtDescriptionKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup EapGroup;
    private javax.swing.ButtonGroup EdpGroup;
    private javax.swing.ButtonGroup EupGroup;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JRadioButton admin1;
    private javax.swing.JRadioButton admin3;
    private javax.swing.JRadioButton admin4;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JButton choosenFileButton;
    private javax.swing.JComboBox<String> choseDepartmentComboBox;
    private javax.swing.JComboBox<String> departmentComboBox;
    private javax.swing.JRadioButton forbidden1;
    private javax.swing.JRadioButton forbidden3;
    private javax.swing.JRadioButton forbidden4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton modify1;
    private javax.swing.JRadioButton modify3;
    private javax.swing.JRadioButton modify4;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JComboBox<String> userComboBox;
    private javax.swing.JRadioButton view1;
    private javax.swing.JRadioButton view3;
    private javax.swing.JRadioButton view4;
    // End of variables declaration//GEN-END:variables
}
