/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Data;
import DAL.DmsException;
import DAL.DmsRepository;
import Model.TableModel;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author vega
 */
public class DeletedFilesForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form DeletedFilesForm
     */
    
    DmsRepository dmsRepository = new DmsRepository();
    TableModel tableModel = new TableModel();
    
    Data data;
    String value;
    int row;
    public DeletedFilesForm() {
        initComponents();
        tabelaLoad();
        getContentPane().setBackground(Color.white);
        sort();
    }
    
    public void sort(){
       javax.swing.table.TableRowSorter<TableModel> sorter = new javax.swing.table.TableRowSorter<>(tableModel);
       tabela.setRowSorter(sorter);
    }
  
    
    private void tabelaLoad(){
        List<Data> data = dmsRepository.findByIsDeleted();
        tableModel.add(data);
        tabela.setModel(tableModel);
        tableModel.fireTableDataChanged();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        undeleteButton = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deleted Documents", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 2, 12))); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 254));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        undeleteButton.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        undeleteButton.setForeground(new java.awt.Color(25, 80, 62));
        undeleteButton.setText("     Undelete");
        undeleteButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 51), null, null));
        undeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undeleteButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(undeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void undeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undeleteButtonMouseClicked
        // TODO add your handling code here:
        try {
            row = tabela.getSelectedRow();
           
            if (row > -1) {
                data = tableModel.getData(row);

                data.setIsDeleted(false);

                dmsRepository.edit(data);
                JOptionPane.showMessageDialog(this, "Document is undeleted");
            }
            tabelaLoad();
        } catch (DmsException pe) {
            JOptionPane.showMessageDialog(this, pe.getMessage());
        }
    }//GEN-LAST:event_undeleteButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel undeleteButton;
    // End of variables declaration//GEN-END:variables
}
