/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author vega
 */
public class DocumentOptions extends javax.swing.JInternalFrame {

    /**
     * Creates new form DocumentOptions
     */
    public DocumentOptions() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deletedButton = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane() {
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(Color.WHITE);
                g.fillRect(0, 0, getWidth(), getHeight());
            }

        };
        rejectionsButton = new javax.swing.JLabel();
        checkedOutButton = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Document Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 2, 12))); // NOI18N
        setClosable(true);
        setIconifiable(true);

        deletedButton.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        deletedButton.setForeground(new java.awt.Color(25, 80, 62));
        deletedButton.setText("       Deleted Files");
        deletedButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 51), null, null));
        deletedButton.setMaximumSize(new java.awt.Dimension(80, 23));
        deletedButton.setMinimumSize(new java.awt.Dimension(80, 23));
        deletedButton.setPreferredSize(new java.awt.Dimension(80, 23));
        deletedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletedButtonMouseClicked(evt);
            }
        });

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(600, 254));
        jDesktopPane1.setName(""); // NOI18N
        jDesktopPane1.setLayout(new javax.swing.BoxLayout(jDesktopPane1, javax.swing.BoxLayout.LINE_AXIS));

        rejectionsButton.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        rejectionsButton.setForeground(new java.awt.Color(25, 80, 62));
        rejectionsButton.setText("        Rejections");
        rejectionsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 51), null, null));
        rejectionsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rejectionsButtonMouseClicked(evt);
            }
        });

        checkedOutButton.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        checkedOutButton.setForeground(new java.awt.Color(25, 80, 62));
        checkedOutButton.setText("  Checked-Out Files");
        checkedOutButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 51), null, null));
        checkedOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkedOutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(deletedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(rejectionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(checkedOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rejectionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkedOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletedButtonMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.updateUI();
        DeletedFilesForm dff = new DeletedFilesForm();
        jDesktopPane1.add(dff);
        dff.show();
    }//GEN-LAST:event_deletedButtonMouseClicked

    private void rejectionsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejectionsButtonMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.updateUI();
        RejectedFiles rjf = new RejectedFiles();
        jDesktopPane1.add(rjf);
        rjf.show();
    }//GEN-LAST:event_rejectionsButtonMouseClicked

    private void checkedOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkedOutButtonMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.updateUI();
        CheckedOutFiles chof = new CheckedOutFiles();
        jDesktopPane1.add(chof);
        chof.show();
                
    }//GEN-LAST:event_checkedOutButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkedOutButton;
    private javax.swing.JLabel deletedButton;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel rejectionsButton;
    // End of variables declaration//GEN-END:variables
}
