/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import BL.Data;
import BL.User;
import DAL.DmsException;
import DAL.DmsRepository;
import Model.TableModel;
import Model.UserTableModel;
import java.awt.Color;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author vesa
 */
public class Review extends javax.swing.JInternalFrame {
    
    DmsRepository dmsRepository = new DmsRepository();
    TableModel tableModel = new TableModel();
    UserTableModel userTableModel = new UserTableModel();
    
    User user;
    Data data;
    int row;
    public String value;
    public Review() {
        initComponents();
        getContentPane().setBackground(Color.white);
        tabelaLoad();
        sort();
    }
    
    /**
     * Creates new form Search
     */
    public void sort(){
       TableRowSorter<TableModel> sorter = new TableRowSorter<>(tableModel);
       tabela.setRowSorter(sorter);
    }
    
    public void emptyObject() {
        tabela.clearSelection();
        txtSubject.setText("");
        txtComment.setText("");
    }
    
    private void tabelaLoad(){
        List<Data> data = dmsRepository.findByStatusReview();
        tableModel.add(data);
        tabela.setModel(tableModel);
        tableModel.fireTableDataChanged();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jLabel4 = new javax.swing.JLabel();
        SearchTxt = new javax.swing.JTextField();
        authorizeButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtComment = new javax.swing.JTextField();
        openButton = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Review", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jLabel4.setText("Search:");

        SearchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTxtActionPerformed(evt);
            }
        });
        SearchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchTxtKeyReleased(evt);
            }
        });

        authorizeButton.setText("Authorize");
        authorizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorizeButtonActionPerformed(evt);
            }
        });

        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jLabel5.setText("Subject:");

        jLabel6.setText("Comment:");

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 682, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(authorizeButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rejectButton)))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(authorizeButton)
                        .addComponent(openButton))
                    .addComponent(rejectButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
     public void filter(String query){
        TableRowSorter<TableModel> tr = new TableRowSorter<>(tableModel);
        tabela.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
     
    private void SearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTxtActionPerformed

    private void SearchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTxtKeyReleased
        String query=SearchTxt.getText();
        filter(query);
    }//GEN-LAST:event_SearchTxtKeyReleased

    private void authorizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorizeButtonActionPerformed
        // TODO add your handling code here:
       try {
            int row = tabela.getSelectedRow();
           
            if (row > -1) {
                Data data = tableModel.getData(row);

                data.setStatus(true);

                dmsRepository.edit(data);

                JOptionPane.showMessageDialog(this, "Document is authorized");
            }
            tabelaLoad();
        } catch (DmsException pe) {
            JOptionPane.showMessageDialog(this, pe.getMessage());
        }
        
    }//GEN-LAST:event_authorizeButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        // TODO add your handling code here:
        if (txtSubject.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter Subject:", "Subject:", JOptionPane.ERROR_MESSAGE); 
        }else if(txtComment.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Comment:", "Comment:", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                row = tabela.getSelectedRow();

                if (row > -1) {
                    data = tableModel.getData(row);
                    value =data.getOwner().getEmail();
                    String subject = txtSubject.getText();
                    String body = txtComment.getText();
                    data.setStatus(false);
                    String [] args = new String[3];
                    args[0] = value;
                    args[1] = subject;
                    args[2] = body;
                    Email.main(args);
                    dmsRepository.edit(data);
                    JOptionPane.showMessageDialog(this, "Document is rejected");
                }
                tabelaLoad();
            } catch (DmsException pe) {
                JOptionPane.showMessageDialog(this, pe.getMessage());
            }
            emptyObject();
        }
    }//GEN-LAST:event_rejectButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        // TODO add your handling code here:
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + value);
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "null");
        }
    }//GEN-LAST:event_openButtonActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        int row = tabela.getSelectedRow();
        value=(tabela.getModel().getValueAt(row, 0).toString());
    }//GEN-LAST:event_tabelaMouseClicked
    
        
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JButton authorizeButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openButton;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JButton rejectButton;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables
}
