/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Category;
import BL.Data;
import BL.Departament;
import BL.User;
import DAL.Categories.CatRepository;
import DAL.Departament.DepException;
import DAL.Departament.DepRepository;
import DAL.DmsException;
import DAL.DmsRepository;
import DAL.FileType.FtRepository;
import Methods.Utils;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import models.CustomComboBoxModel;

/**
 *
 * @author vega
 */
public class UserAddDocument extends javax.swing.JInternalFrame {
    
        CatRepository catRepository = new CatRepository();
        DmsRepository dmsRepository = new DmsRepository();
        DepRepository depRepository = new DepRepository();
        FtRepository ftRepository = new FtRepository();
        
        CustomComboBoxModel userComboBoxModel = null;
        CustomComboBoxModel departamentComboBoxModel = null;
        CustomComboBoxModel categoryComboBoxModel = null;
        
        List <String> allowedFileTypes;
        
        String Path = null;
        Path target =null;
        String filename = null; 
        File choosenFile = null;
        
        JFileChooser chooser = new JFileChooser();
        
        public User usi;
        
    public UserAddDocument()
    {
        usi = UserMainForm.us;
        initComponents();
        this.allowedFileTypes = ftRepository.fileTypes();
        getContentPane().setBackground(Color.white);
        loadComboBoxs();
    }
    
    public void emptyObject() {
        chooser.cancelSelection();
        target = null;
        categoryComboBox.setSelectedItem(null);
        categoryComboBox.repaint();
        txtDescription.setText("");
    }
    
    public void loadComboBoxs()
    {
        List <Category> category = catRepository.findAll();
        
        categoryComboBoxModel = new CustomComboBoxModel(category);
        
        categoryComboBox.setModel(categoryComboBoxModel);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        forbidden3 = new javax.swing.JRadioButton();
        forbidden4 = new javax.swing.JRadioButton();
        view4 = new javax.swing.JRadioButton();
        modify3 = new javax.swing.JRadioButton();
        modify4 = new javax.swing.JRadioButton();
        view3 = new javax.swing.JRadioButton();
        admin3 = new javax.swing.JRadioButton();
        admin4 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Document", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 2, 12))); // NOI18N
        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("File Location ");

        jButton1.setText("Choose Files");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Category");

        jLabel12.setText(" Edit User Permissions");

        jLabel14.setText("User, Admin");

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categories" }));

        jLabel15.setText("User, User");

        jLabel5.setText("Permissions");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("  Forbidden");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(" View");
        jLabel17.setPreferredSize(new java.awt.Dimension(54, 14));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Modify");
        jLabel18.setPreferredSize(new java.awt.Dimension(54, 14));
        jLabel18.setVerifyInputWhenFocusTarget(false);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(" Admin");
        jLabel19.setPreferredSize(new java.awt.Dimension(54, 14));

        forbidden3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forbidden3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        view4.setSelected(true);

        modify3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modify3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modify3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify3ActionPerformed(evt);
            }
        });

        view3.setSelected(true);

        admin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setText("Description");

        submitButton.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(forbidden3)
                                                    .addComponent(forbidden4)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(jLabel16)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(view3)
                                                    .addComponent(view4))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(modify3)
                                                    .addComponent(modify4))
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(admin4)
                                                    .addComponent(admin3)))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(forbidden3)
                            .addComponent(modify3)
                            .addComponent(admin3)))
                    .addComponent(view3))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(forbidden4)
                    .addComponent(view4)
                    .addComponent(modify4)
                    .addComponent(admin4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        choosenFile = chooseFile();
        
        if(choosenFile == null)
        {
            return;
        }
        
        if(choosenFile.length() > 262144000)//250*1024*1024=262144000
        {
            chooser.cancelSelection();
            choosenFile = null;
           
            JOptionPane.showMessageDialog(this, "Files larger than 250MB are not allowed!");
            return;
        }
        
        if (! isAllowedFile(choosenFile))
        {
            chooser.cancelSelection();
            choosenFile = null;
            
            JOptionPane.showMessageDialog(this, "This file type is not allowed");
            return;
        }

        Path movefrom = Utils.getPathFrom(choosenFile);

        Utils.makeDirIfNotExists("C:\\DMS-Files\\");
        
        target = FileSystems.getDefault().getPath("C:\\DMS-Files\\" + Utils.getUniqueName(choosenFile.getName()));

        try{
            Files.copy(movefrom, target, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException ex) {
            Logger.getLogger(AddDocument.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
     private boolean isAllowedFile(File file) 
    {
        return allowedFileTypes.contains(Utils.getFileExtension(file));
    }
    
    private File chooseFile()
    {
        int returnVal = chooser.showOpenDialog(null);
        return chooser.getSelectedFile();
    }
    
    private void modify3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modify3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modify3ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
    try{
        if (choosenFile == null) {
            JOptionPane.showMessageDialog(this, "Please select a File:", "File:", JOptionPane.ERROR_MESSAGE);
        }else if (target == null) {
            JOptionPane.showMessageDialog(this, "Please select a File:", "File:", JOptionPane.ERROR_MESSAGE);
        }else if (categoryComboBox.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Please choose the Category:", "Category:", JOptionPane.ERROR_MESSAGE);
        }else if (txtDescription.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please choose the Description:", "Description:", JOptionPane.ERROR_MESSAGE);
        }else{
            if(!((choosenFile == null)||(target == null)||(categoryComboBox.getSelectedIndex() == -1)||(txtDescription.getText().equals(""))))
            {
                Data data = new Data();

                Category category = (Category) categoryComboBox.getSelectedItem();
                Departament departament = null;
                    try{
                    departament = depRepository.findById(usi.getDepartment());
                    }catch (DepException ex) {
                        Logger.getLogger(AddUsers.class.getName()).log(Level.SEVERE, null, ex);
                    }
                data.setCategory(category);

                data.setCreated(new Date());

                data.setOwner(usi);

                data.setDescription(txtDescription.getText());

                data.setStatus(null);

                data.setDepartment(departament);

                data.setIsDeleted(false);

                data.setPath(target.toString());

                data.setRealname(choosenFile.getName());

                JOptionPane.showMessageDialog(null, "Document is saved successfully." );

                dmsRepository.create(data);
            }
            emptyObject();
        }
    } catch (DmsException ex) {
        Logger.getLogger(AddDocument.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin3;
    private javax.swing.JRadioButton admin4;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JRadioButton forbidden3;
    private javax.swing.JRadioButton forbidden4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton modify3;
    private javax.swing.JRadioButton modify4;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JRadioButton view3;
    private javax.swing.JRadioButton view4;
    // End of variables declaration//GEN-END:variables
}
