/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Data;
import DAL.DmsRepository;
import Model.TableModel;
import java.awt.Color;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vesa
 */
public class UserHomeForm extends javax.swing.JInternalFrame {
    
    DmsRepository dmsRepository = new DmsRepository();
    TableModel tableModel = new TableModel();

    Data data;
    String value;
    int row;
    
    public UserHomeForm(){
        initComponents();
        tabelaLoad();
        sort();
        getContentPane().setBackground(Color.white);
    }
    
    public void sort(){
       TableRowSorter<TableModel> sorter = new TableRowSorter<>(tableModel);
       tabela.setRowSorter(sorter);
    }
  
    
    private void tabelaLoad(){
        List<Data> data = dmsRepository.findByStatus();
        tableModel.add(data);
        tabela.setModel(tableModel);
        tableModel.fireTableDataChanged();

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DMSPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("DMSPU").createEntityManager();
        dataQuery = java.beans.Beans.isDesignTime() ? null : DMSPUEntityManager.createQuery("SELECT d FROM Data d");
        dataList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dataQuery.getResultList();
        dataQuery1 = java.beans.Beans.isDesignTime() ? null : DMSPUEntityManager.createQuery("SELECT d FROM Data d");
        dataList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dataQuery1.getResultList();
        dataQuery2 = java.beans.Beans.isDesignTime() ? null : DMSPUEntityManager.createQuery("SELECT d FROM Data d");
        dataList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dataQuery2.getResultList();
        dataQuery3 = java.beans.Beans.isDesignTime() ? null : DMSPUEntityManager.createQuery("SELECT d FROM Data d");
        dataList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dataQuery3.getResultList();
        dataQuery4 = java.beans.Beans.isDesignTime() ? null : DMSPUEntityManager.createQuery("SELECT d FROM Data d");
        dataList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dataQuery4.getResultList();
        dataQuery5 = java.beans.Beans.isDesignTime() ? null : DMSPUEntityManager.createQuery("SELECT d FROM Data d");
        dataList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dataQuery5.getResultList();
        dataQuery6 = java.beans.Beans.isDesignTime() ? null : DMSPUEntityManager.createQuery("SELECT d FROM Data d");
        dataList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : dataQuery6.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SearchTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        openButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(920, 490));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        SearchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchTxtKeyReleased(evt);
            }
        });

        jLabel4.setText("Search:");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(openButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(openButton)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        row = tabela.getSelectedRow();
        value=(tabela.getModel().getValueAt(row, 0).toString());
    }//GEN-LAST:event_tabelaMouseClicked
    
    public void filter(String query)
    {
        TableRowSorter<TableModel> tr = new TableRowSorter<>(tableModel);
        tabela.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    private void SearchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTxtKeyReleased
        String query=SearchTxt.getText();
        filter(query);
    }//GEN-LAST:event_SearchTxtKeyReleased

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        // TODO add your handling code here:
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + value);
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "null");
        }
    }//GEN-LAST:event_openButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager DMSPUEntityManager;
    private javax.swing.JTextField SearchTxt;
    private java.util.List<BL.Data> dataList;
    private java.util.List<BL.Data> dataList1;
    private java.util.List<BL.Data> dataList2;
    private java.util.List<BL.Data> dataList3;
    private java.util.List<BL.Data> dataList4;
    private java.util.List<BL.Data> dataList5;
    private java.util.List<BL.Data> dataList6;
    private javax.persistence.Query dataQuery;
    private javax.persistence.Query dataQuery1;
    private javax.persistence.Query dataQuery2;
    private javax.persistence.Query dataQuery3;
    private javax.persistence.Query dataQuery4;
    private javax.persistence.Query dataQuery5;
    private javax.persistence.Query dataQuery6;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton openButton;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
